name: Retrain ML Model

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  retrain:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.12"

    - name: Install dependencies

      run: |
        pip install -r MLProject/requirements.txt

    - name: Run MLflow Project

      run: |
       cd MLProject
        mlflow run . --env-manager local
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/best_model.pkl